In [9]:
import pandas as pd
from DataStructure import ChampionNetwork
import numpy as np
import matplotlib.pyplot as plt
import networkx as nx
import matplotlib.pyplot as plt
from flask import Flask

In [10]:
# pip install flask

In [11]:
game = pd.read_csv('games.csv')

In [12]:
game.columns

Index(['gameId', 'creationTime', 'gameDuration', 'seasonId', 'winner',
       'firstBlood', 'firstTower', 'firstInhibitor', 'firstBaron',
       'firstDragon', 'firstRiftHerald', 't1_champ1id', 't1_champ1_sum1',
       't1_champ1_sum2', 't1_champ2id', 't1_champ2_sum1', 't1_champ2_sum2',
       't1_champ3id', 't1_champ3_sum1', 't1_champ3_sum2', 't1_champ4id',
       't1_champ4_sum1', 't1_champ4_sum2', 't1_champ5id', 't1_champ5_sum1',
       't1_champ5_sum2', 't1_towerKills', 't1_inhibitorKills', 't1_baronKills',
       't1_dragonKills', 't1_riftHeraldKills', 't1_ban1', 't1_ban2', 't1_ban3',
       't1_ban4', 't1_ban5', 't2_champ1id', 't2_champ1_sum1', 't2_champ1_sum2',
       't2_champ2id', 't2_champ2_sum1', 't2_champ2_sum2', 't2_champ3id',
       't2_champ3_sum1', 't2_champ3_sum2', 't2_champ4id', 't2_champ4_sum1',
       't2_champ4_sum2', 't2_champ5id', 't2_champ5_sum1', 't2_champ5_sum2',
       't2_towerKills', 't2_inhibitorKills', 't2_baronKills', 't2_dragonKills',
       't2_riftHeraldKills', 't2_ban1', 't2_ban2', 't2_ban3', 't2_ban4',
       't2_ban5'],
      dtype='object')

In [13]:
# check for the null values
game.isnull().sum() # no null values

gameId          0
creationTime    0
gameDuration    0
seasonId        0
winner          0
               ..
t2_ban1         0
t2_ban2         0
t2_ban3         0
t2_ban4         0
t2_ban5         0
Length: 61, dtype: int64

In [14]:
# check for the data types
game.describe()

,gameId,creationTime,gameDuration,seasonId,winner,firstBlood,firstTower,firstInhibitor,firstBaron,firstDragon,...,t2_towerKills,t2_inhibitorKills,t2_baronKills,t2_dragonKills,t2_riftHeraldKills,t2_ban1,t2_ban2,t2_ban3,t2_ban4,t2_ban5
count,5.149000e+04,5.149000e+04,51490.000000,51490.0,51490.000000,51490.000000,51490.000000,51490.000000,51490.000000,51490.000000,...,51490.000000,51490.000000,51490.000000,51490.000000,51490.000000,51490.000000,51490.000000,51490.000000,51490.000000,51490.000000
mean,3.306223e+09,1.502926e+12,1832.362808,9.0,1.493552,1.471295,1.450631,1.308487,0.926510,1.442804,...,5.549466,0.985084,0.414547,1.404370,0.240105,108.216294,107.910216,108.690581,108.626044,108.066576
std,2.946096e+07,1.978026e+09,512.017696,0.0,0.499963,0.520326,0.542848,0.676097,0.841424,0.569579,...,3.860989,1.256284,0.613768,1.224492,0.427151,102.551787,102.870710,102.592145,103.346952,102.756149
min,3.214824e+09,1.496892e+12,190.000000,9.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,3.292218e+09,1.502021e+12,1531.000000,9.0,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,...,2.000000,0.000000,0.000000,0.000000,0.000000,38.000000,37.000000,38.000000,38.000000,38.000000
50%,3.320021e+09,1.503844e+12,1833.000000,9.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,6.000000,0.000000,0.000000,1.000000,0.000000,90.000000,90.000000,90.000000,90.000000,90.000000
75%,3.327099e+09,1.504352e+12,2148.000000,9.0,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,9.000000,2.000000,1.000000,2.000000,0.000000,141.000000,141.000000,141.000000,141.000000,141.000000
max,3.331833e+09,1.504707e+12,4728.000000,9.0,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,11.000000,10.000000,4.000000,6.000000,1.000000,516.000000,516.000000,516.000000,516.000000,516.000000

In [15]:
# get the data types for all
game.dtypes

gameId          int64
creationTime    int64
gameDuration    int64
seasonId        int64
winner          int64
                ...
t2_ban1         int64
t2_ban2         int64
t2_ban3         int64
t2_ban4         int64
t2_ban5         int64
Length: 61, dtype: object

In [16]:
game_data = game
champ_network = ChampionNetwork(game_data=game_data)

while True:
    print("\n1. Query a Champion")
    print("2. View Most Common Champion Pairs")
    print("3. Most Influential Champions")
    print("4. Find Isolated Champions")

    choice = input("Choose an option or 'q' to quit: ")

    if choice == "q":
        break
    elif choice == "1":
        champ_id = int(input("Enter Champion ID: "))
        print(champ_network.query_champion(champ_id))
    elif choice == "2":
        print(champ_network.common_pairs())
    elif choice == "3":
        print(champ_network.most_influential_champions())
    elif choice == '4':
        isolated = champ_network.find_isolated_champions()
        if not isolated:
            print("No isolated champions found.")
        else:
            print("Isolated Champions:", isolated)

1. Query a Champion
2. View Most Common Champion Pairs
3. Most Influential Champions
4. Find Isolated Champions
{432: {'weight': 117}, 96: {'weight': 99}, 11: {'weight': 173}, 112: {'weight': 15}, 89: {'weight': 152}, 29: {'weight': 308}, 104: {'weight': 47}, 157: {'weight': 164}, 81: {'weight': 153}, 161: {'weight': 51}, 267: {'weight': 131}, 64: {'weight': 276}, 18: {'weight': 439}, 201: {'weight': 115}, 103: {'weight': 67}, 254: {'weight': 79}, 67: {'weight': 293}, 57: {'weight': 110}, 59: {'weight': 195}, 429: {'weight': 120}, 122: {'weight': 61}, 51: {'weight': 196}, 15: {'weight': 118}, 497: {'weight': 223}, 412: {'weight': 398}, 238: {'weight': 139}, 56: {'weight': 52}, 31: {'weight': 95}, 516: {'weight': 111}, 119: {'weight': 143}, 245: {'weight': 67}, 53: {'weight': 198}, 236: {'weight': 290}, 126: {'weight': 66}, 9: {'weight': 46}, 45: {'weight': 62}, 117: {'weight': 220}, 40: {'weight': 319}, 24: {'weight': 190}, 121: {'weight': 166}, 41: {'weight': 87}, 154: {'weight': 92}, 80: {'weight': 62}, 85: {'weight': 27}, 63: {'weight': 85}, 141: {'weight': 341}, 113: {'weight': 122}, 37: {'weight': 170}, 19: {'weight': 169}, 98: {'weight': 68}, 33: {'weight': 95}, 69: {'weight': 27}, 16: {'weight': 185}, 25: {'weight': 143}, 92: {'weight': 113}, 105: {'weight': 39}, 202: {'weight': 244}, 1: {'weight': 47}, 83: {'weight': 21}, 22: {'weight': 164}, 107: {'weight': 61}, 68: {'weight': 32}, 44: {'weight': 81}, 43: {'weight': 79}, 82: {'weight': 25}, 23: {'weight': 60}, 21: {'weight': 172}, 498: {'weight': 252}, 102: {'weight': 80}, 111: {'weight': 58}, 203: {'weight': 42}, 91: {'weight': 88}, 4: {'weight': 48}, 36: {'weight': 24}, 12: {'weight': 109}, 35: {'weight': 71}, 54: {'weight': 49}, 110: {'weight': 85}, 77: {'weight': 32}, 7: {'weight': 25}, 3: {'weight': 52}, 58: {'weight': 94}, 143: {'weight': 61}, 39: {'weight': 62}, 48: {'weight': 49}, 17: {'weight': 72}, 222: {'weight': 228}, 131: {'weight': 46}, 427: {'weight': 30}, 150: {'weight': 78}, 90: {'weight': 44}, 421: {'weight': 45}, 74: {'weight': 29}, 62: {'weight': 65}, 28: {'weight': 40}, 79: {'weight': 182}, 86: {'weight': 72}, 75: {'weight': 67}, 223: {'weight': 44}, 34: {'weight': 35}, 6: {'weight': 45}, 42: {'weight': 44}, 268: {'weight': 23}, 133: {'weight': 44}, 120: {'weight': 54}, 55: {'weight': 38}, 20: {'weight': 43}, 78: {'weight': 40}, 27: {'weight': 17}, 115: {'weight': 37}, 99: {'weight': 100}, 114: {'weight': 47}, 5: {'weight': 77}, 164: {'weight': 42}, 266: {'weight': 21}, 60: {'weight': 61}, 84: {'weight': 41}, 240: {'weight': 46}, 420: {'weight': 17}, 134: {'weight': 29}, 61: {'weight': 65}, 10: {'weight': 32}, 76: {'weight': 38}, 127: {'weight': 15}, 106: {'weight': 23}, 26: {'weight': 45}, 32: {'weight': 70}, 2: {'weight': 26}, 14: {'weight': 42}, 38: {'weight': 37}, 101: {'weight': 26}, 13: {'weight': 9}, 30: {'weight': 7}, 50: {'weight': 22}, 163: {'weight': 22}, 72: {'weight': 21}, 136: {'weight': 13}}

1. Query a Champion
2. View Most Common Champion Pairs
3. Most Influential Champions
4. Find Isolated Champions
[(498, 497, {'weight': 2362}), (412, 18, {'weight': 1541}), (412, 67, {'weight': 1372}), (18, 40, {'weight': 1266}), (18, 141, {'weight': 1207}), (412, 141, {'weight': 1176}), (412, 64, {'weight': 1145}), (412, 202, {'weight': 1139}), (412, 236, {'weight': 1132}), (18, 64, {'weight': 1112})]

1. Query a Champion
2. View Most Common Champion Pairs
3. Most Influential Champions
4. Find Isolated Champions
[(8, 1.0), (432, 1.0), (498, 1.0), (96, 1.0), (122, 1.0), (11, 1.0), (238, 1.0), (112, 1.0), (412, 1.0), (119, 1.0), (39, 1.0), (54, 1.0), (25, 1.0), (76, 1.0), (10, 1.0), (157, 1.0), (35, 1.0), (92, 1.0), (18, 1.0), (141, 1.0), (69, 1.0), (267, 1.0), (126, 1.0), (68, 1.0), (24, 1.0), (38, 1.0), (22, 1.0), (57, 1.0), (63, 1.0), (90, 1.0), (19, 1.0), (29, 1.0), (61, 1.0), (36, 1.0), (37, 1.0), (59, 1.0), (40, 1.0), (134, 1.0), (51, 1.0), (15, 1.0), (245, 1.0), (45, 1.0), (2, 1.0), (67, 1.0), (12, 1.0), (74, 1.0), (17, 1.0), (53, 1.0), (21, 1.0), (114, 1.0), (161, 1.0), (150, 1.0), (64, 1.0), (16, 1.0), (497, 1.0), (79, 1.0), (111, 1.0), (99, 1.0), (427, 1.0), (110, 1.0), (75, 1.0), (429, 1.0), (131, 1.0), (86, 1.0), (236, 1.0), (7, 1.0), (143, 1.0), (105, 1.0), (89, 1.0), (4, 1.0), (33, 1.0), (5, 1.0), (1, 1.0), (421, 1.0), (202, 1.0), (81, 1.0), (84, 1.0), (103, 1.0), (23, 1.0), (55, 1.0), (113, 1.0), (82, 1.0), (31, 1.0), (222, 1.0), (50, 1.0), (44, 1.0), (42, 1.0), (41, 1.0), (117, 1.0), (6, 1.0), (9, 1.0), (56, 1.0), (27, 1.0), (78, 1.0), (164, 1.0), (91, 1.0), (3, 1.0), (201, 1.0), (14, 1.0), (62, 1.0), (83, 1.0), (13, 1.0), (240, 1.0), (223, 1.0), (254, 1.0), (48, 1.0), (154, 1.0), (43, 1.0), (34, 1.0), (107, 1.0), (85, 1.0), (58, 1.0), (20, 1.0), (98, 1.0), (136, 1.0), (516, 1.0), (80, 1.0), (420, 1.0), (106, 1.0), (26, 1.0), (133, 1.0), (115, 1.0), (266, 1.0), (102, 1.0), (30, 1.0), (104, 0.9927007299270073), (32, 0.9927007299270073), (101, 0.9927007299270073), (268, 0.9927007299270073), (121, 0.9927007299270073), (163, 0.9927007299270073), (60, 0.9927007299270073), (77, 0.9927007299270073), (127, 0.9927007299270073), (203, 0.9927007299270073), (120, 0.9854014598540146), (28, 0.9854014598540146), (72, 0.9708029197080291)]

1. Query a Champion
2. View Most Common Champion Pairs
3. Most Influential Champions
4. Find Isolated Champions
No isolated champions found.

1. Query a Champion
2. View Most Common Champion Pairs
3. Most Influential Champions
4. Find Isolated Champions